# Generated by Django 4.2.1 on 2023-05-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
