# Generated by Django 4.2.1 on 2023-05-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
