version: '3.9'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  
  app:
    restart: always
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - MEDIA_ROOT=/usr/src/app/images
    ports:
      - 147.182.218.0:8000
    volumes:
      - ./images/:/usr/src/app/static/images